version: "3.8"

services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.db.address=:5432"
    ports:
      - "80:80"
      - "8080:8080"
      - "5432:5432"
    volumes:
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro

  app-stable:
    build: .
    environment:
      - VERSION=1.0.0
      - STATUS=STABLE

  app-canary:
    build: .
    labels:
      - "traefik.enable=true"
    environment:
      - VERSION=2.0.0
      - STATUS=CANARY
